{
  logger.error("unhandled exception caught",exception);
}
